# SPDX-FileCopyrightText: 2022 Luke Murphy
#
# SPDX-License-Identifier: MIT

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up Node for interop testing
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Build smoke test
      run: go build -v ./...

    - name: Build arm smoke test
      run: GOARCH=arm go build -v ./...

    - name: Install node ssb-stack
      run: npm ci --prefer-offline --no-audit

    - name: Test
      run: go test -v ./...
